name: Trivy scan for DVWA
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *
jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build DVWA Docker image
        run: docker build -t dvwa .
      - name: Run Trivy security scan
        uses: aquasecurity/trivy-action@v0.7.0
        with:
          image-ref: dvwa
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
      - name: Run DVWA container
        run: 'docker run -d --name dvwa -p 80:80 dvwa'
      - name: Check running containers
        run: docker ps
      - name: Stop and remove DVWA container
        run: |
          docker stop dvwa
          docker rm dvwa
