name: Trivy scan for DVWA
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *
jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
      - name: Install Trivy
        run: >
          sudo apt-get install wget -y

          wget
          https://github.com/aquasecurity/trivy/releases/latest/download/trivy_amd64.deb

          sudo dpkg -i trivy_amd64.deb
      - name: Build Docker Image
        run: docker build -t dvwa .
      - name: Run Trivy Image Scan
        run: 'trivy image --exit-code 1 --severity CRITICAL,HIGH dvwa'
